// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQ_KjX1pRU2wAFeYddlsmmADa-Gr3lGo',
    appId: '1:95895499587:web:5382302a987bea30b875f6',
    messagingSenderId: '95895499587',
    projectId: 'wekend-masti-c9bb4',
    authDomain: 'wekend-masti-c9bb4.firebaseapp.com',
    storageBucket: 'wekend-masti-c9bb4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDim3MTIwwjj4DibKSRiTFhccT4aSnPY1M',
    appId: '1:95895499587:android:f9dbae180859b2e1b875f6',
    messagingSenderId: '95895499587',
    projectId: 'wekend-masti-c9bb4',
    storageBucket: 'wekend-masti-c9bb4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyd0CR4Cf6dspraw2UldZVDh2YzQGGcY0',
    appId: '1:95895499587:ios:1b9e699092674fc7b875f6',
    messagingSenderId: '95895499587',
    projectId: 'wekend-masti-c9bb4',
    storageBucket: 'wekend-masti-c9bb4.firebasestorage.app',
    iosBundleId: 'com.example.wm',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyd0CR4Cf6dspraw2UldZVDh2YzQGGcY0',
    appId: '1:95895499587:ios:1b9e699092674fc7b875f6',
    messagingSenderId: '95895499587',
    projectId: 'wekend-masti-c9bb4',
    storageBucket: 'wekend-masti-c9bb4.firebasestorage.app',
    iosBundleId: 'com.example.wm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRQ_KjX1pRU2wAFeYddlsmmADa-Gr3lGo',
    appId: '1:95895499587:web:25fedb70c252ea35b875f6',
    messagingSenderId: '95895499587',
    projectId: 'wekend-masti-c9bb4',
    authDomain: 'wekend-masti-c9bb4.firebaseapp.com',
    storageBucket: 'wekend-masti-c9bb4.firebasestorage.app',
  );
}
